version: '3.4'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        networks:
            - frontend
        volumes:
            - ${PROJECT_PATH}:/var/www/html
            - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
            - ./nginx/logs:/var/log/nginx/
        depends_on:
            - app

    app:
        build: ./php
        networks:
            - backend
            - frontend
        volumes:
            - ${PROJECT_PATH}:/var/www/html
        depends_on:
            - db

    db:
        image: mariadb
        ports:
            - "3306:3306"
        networks:
            - backend
        volumes:
            - ./db/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=luck4me
            - MYSQL_PASSWORD=secret
            - MYSQL_DATABASE=luck4me

networks:
    backend:
    frontend:
